import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

/// ---- The following is required to prevent CSS for icons coming in too late and looking odd ----
import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
config.autoAddCss = false
/// --------------------------------------------------------------------------------------------------------

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Meal Planner",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
